server:
  env: debug        # debug/test/release
  name: ego-layout
  version: v1
  port: 10023
  readTimeout: 10     # 读等待时间，单位: 秒
  writeTimeout: 10    # 写等待时间，单位: 秒
log:
  path: ./logs        # 日志目录, 不要在最后加/
  bizMaxAge: 7        # 指定保留多少天的业务日志
  bizErrMaxAge: 7     # 指定保留多少天的业务错误日志
  callMaxAge: 7       # 指定保留多少天的请求日志
  minLevel: debug     # 日志级别：debug、info、warn、error
mysql:
  MYSQLKEY:
    host: 127.0.0.1
    database: database
    port: 3306
    user: root
    password: password
    params: parseTime=True
redis:
  expire: 24          # 缓存有效期，单位:小时
  deviation: 5        # 随机偏移范围,例如 expire=24&deviation=1 => 真正过期时间在23~25h之间随机
  REDISKEY:
    network: tcp
    host: 127.0.0.1
    port: 6379
    password:
    db: 0               # 数据库
    maxIdle: 20         # 最大空闲连接数
    maxActive: 500      # 连接池最大数目,为0则不限制
    idleTimeout: 60     # 空闲连接超时时间，超过时间的空闲连接会被关闭,为0将不会被关闭,应该设置一个比redis服务端超时时间更短的时间，单位: 秒
    wait: true          # 如果为true且已经达到MaxActive的限制，则等待连接池，为false将直接返回错误
    maxConnLifeTime: 0  # 一个连接的生命时长，超时而且没被使用则被释放, 如果为0则不根据生命周期来关闭连接，单位: 秒
jwt:
  expire: 24          # token有效期，单位:小时
